const http=require('http'),fetch=require('node-fetch'),{Storage}=require('@google-cloud/storage'),PORT=process.env.PORT||8080,LOCATION='us-central1',MODEL='veo-3.1-generate-001';
async function getProjectId(){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/project/project-id',{headers:{'Metadata-Flavor':'Google'}});return r.text();}
async function getAccessToken(){const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'}});return(await r.json()).access_token;}
let PROJECT=null,storage=null,BUCKET=null;
async function init(){PROJECT=await getProjectId();BUCKET='studio-cinema-'+PROJECT;storage=new Storage({projectId:PROJECT});try{await storage.createBucket(BUCKET,{location:'EU'});}catch(e){}}
async function saveToGCS(b64,fn){const f=storage.bucket(BUCKET).file(fn);await f.save(Buffer.from(b64,'base64'),{contentType:'video/mp4',metadata:{cacheControl:'public, max-age=3600'}});return`https://storage.googleapis.com/${BUCKET}/${fn}`;}
const server=http.createServer(function(req,res){
res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','POST,GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');
if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
if(req.method==='GET'&&req.url.startsWith('/download')){const u=new URL(req.url,'http://localhost').searchParams.get('url');if(!u){res.writeHead(400);res.end('URL manquante');return;}fetch(u).then(v=>{res.writeHead(200,{'Content-Type':'video/mp4','Content-Disposition':'attachment; filename="video.mp4"','Access-Control-Allow-Origin':'*'});v.body.pipe(res);}).catch(e=>{res.writeHead(500);res.end(e.message);});return;}
if(req.method!=='POST'){res.writeHead(405);res.end('{}');return;}
let body='';req.on('data',c=>body+=c);req.on('end',async function(){
try{const p=JSON.parse(body);const apiKey=(p.apiKey||'').trim();if(!apiKey){res.writeHead(400);res.end(JSON.stringify({error:'apiKey requis'}));return;}
const token=await getAccessToken();
if(req.url==='/generate'){const url=`https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT}/locations/${LOCATION}/publishers/google/models/${MODEL}:predictLongRunning`;const vr=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(p.body)});const txt=await vr.text();let data;try{data=JSON.parse(txt);}catch(e){res.writeHead(500);res.end(JSON.stringify({error:txt.slice(0,300)}));return;}if(!vr.ok){res.writeHead(vr.status);res.end(JSON.stringify({error:(data.error&&data.error.message)||txt.slice(0,200)}));return;}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(data));}
else if(req.url==='/poll'){const url=`https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT}/locations/${LOCATION}/publishers/google/models/${MODEL}:fetchPredictOperation`;const vr=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({operationName:p.operationName})});const txt=await vr.text();let data;try{data=JSON.parse(txt);}catch(e){res.writeHead(500);res.end(JSON.stringify({error:txt.slice(0,300)}));return;}if(!vr.ok){res.writeHead(vr.status);res.end(JSON.stringify({error:(data.error&&data.error.message)||txt.slice(0,200)}));return;}if(data.done&&data.raiMediaFiltered){res.writeHead(200);res.end(JSON.stringify({done:true,error:'Image refusee.'}));return;}if(data.done&&data.response){let b=null,r=data.response;if(r.videos&&r.videos[0])b=r.videos[0].bytesBase64Encoded;else if(r.predictions&&r.predictions[0])b=r.predictions[0].bytesBase64Encoded;if(b){try{const fn='video-'+Date.now()+'.mp4';const vu=await saveToGCS(b,fn);res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({done:true,videoUrl:vu}));return;}catch(e){console.log('GCS:',e.message);}}}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(data));}
else{res.writeHead(404);res.end(JSON.stringify({error:'Route inconnue'}));}}catch(e){res.writeHead(500);res.end(JSON.stringify({error:e.message}));}});});
init().then(()=>server.listen(PORT,()=>console.log('OK port',PORT,'projet',PROJECT)));
